# Generated by Django 5.2.7 on 2026-06-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
                ('servizio', models.CharField(choices=[('taglio', 'Taglio'), ('barba', 'Barba'), ('combo', 'Taglio + Barba')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('data', 'ora')},
            },
        ),
    ]
