# Generated by Django 5.2.7 on 2026-06-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completata',
            field=models.BooleanField(default=False),
        ),
    ]
